//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMIS.DEMO.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISAResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISAResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMIS.DEMO.Core.Resources.MISAResources", typeof(MISAResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to employee.
        /// </summary>
        public static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Enum_Female {
            get {
                return ResourceManager.GetString("Enum_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Enum_Male {
            get {
                return ResourceManager.GetString("Enum_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Enum_Other {
            get {
                return ResourceManager.GetString("Enum_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address must not exceed 255 characters.
        /// </summary>
        public static string InValidMsg_AddressTooLong {
            get {
                return ResourceManager.GetString("InValidMsg_AddressTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        public static string InValidMsg_AuthenticationFail {
            get {
                return ResourceManager.GetString("InValidMsg_AuthenticationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account must not exceed 20 characters.
        /// </summary>
        public static string InValidMsg_BankAccountTooLong {
            get {
                return ResourceManager.GetString("InValidMsg_BankAccountTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank branch must not exceed 100 characters.
        /// </summary>
        public static string InValidMsg_BankBranchTooLong {
            get {
                return ResourceManager.GetString("InValidMsg_BankBranchTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank name must not exceed 100 characters.
        /// </summary>
        public static string InValidMsg_BankNameTooLong {
            get {
                return ResourceManager.GetString("InValidMsg_BankNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get new code. Please try again later.
        /// </summary>
        public static string InValidMsg_CantGetNewCode {
            get {
                return ResourceManager.GetString("InValidMsg_CantGetNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data is empty.
        /// </summary>
        public static string InValidMsg_DataImportIsEmpty {
            get {
                return ResourceManager.GetString("InValidMsg_DataImportIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue date is not in correct date format.
        /// </summary>
        public static string InValidMsg_DateIdentityInvalid {
            get {
                return ResourceManager.GetString("InValidMsg_DateIdentityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected date cannot be greater than the current date.
        /// </summary>
        public static string InValidMsg_DateMustBefore {
            get {
                return ResourceManager.GetString("InValidMsg_DateMustBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is not in correct date format.
        /// </summary>
        public static string InValidMsg_DateOfBirthInvalid {
            get {
                return ResourceManager.GetString("InValidMsg_DateOfBirthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect date format.
        /// </summary>
        public static string InValidMsg_DateType {
            get {
                return ResourceManager.GetString("InValidMsg_DateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department code is required.
        /// </summary>
        public static string InValidMsg_DepartmentCodeRequired {
            get {
                return ResourceManager.GetString("InValidMsg_DepartmentCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department code must not exceed 20 characters..
        /// </summary>
        public static string InValidMsg_DepartmentCodeTooLong {
            get {
                return ResourceManager.GetString("InValidMsg_DepartmentCodeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid department.
        /// </summary>
        public static string InValidMsg_DepartmentInvalid {
            get {
                return ResourceManager.GetString("InValidMsg_DepartmentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name is required.
        /// </summary>
        public static string InValidMsg_DepartmentNameRequired {
            get {
                return ResourceManager.GetString("InValidMsg_DepartmentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department is required.
        /// </summary>
        public static string InValidMsg_DepartmentRequired {
            get {
                return ResourceManager.GetString("InValidMsg_DepartmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code &lt;{0}&gt; already exists in the system.
        /// </summary>
        public static string InValidMsg_DuplicateEmployeeCode {
            get {
                return ResourceManager.GetString("InValidMsg_DuplicateEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate error.
        /// </summary>
        public static string InValidMsg_DuplicateInput {
            get {
                return ResourceManager.GetString("InValidMsg_DuplicateInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number &lt;{0}&gt; is registered.
        /// </summary>
        public static string InValidMsg_DuplicatePhoneNumber {
            get {
                return ResourceManager.GetString("InValidMsg_DuplicatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must not exceed 100 characters.
        /// </summary>
        public static string InValidMsg_EmailTooLong {
            get {
                return ResourceManager.GetString("InValidMsg_EmailTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee code already exists in the system.
        /// </summary>
        public static string InValidMsg_EmployeeCodeInvalidImport {
            get {
                return ResourceManager.GetString("InValidMsg_EmployeeCodeInvalidImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee code already exists on the import file.
        /// </summary>
        public static string InValidMsg_EmployeeCodeInvalidImportInFile {
            get {
                return ResourceManager.GetString("InValidMsg_EmployeeCodeInvalidImportInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code is required.
        /// </summary>
        public static string InValidMsg_EmployeeCodeRequired {
            get {
                return ResourceManager.GetString("InValidMsg_EmployeeCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code must not exceed 20 characters.
        /// </summary>
        public static string InValidMsg_EmployeeCodeTooLong {
            get {
                return ResourceManager.GetString("InValidMsg_EmployeeCodeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not in the correct format provided.
        /// </summary>
        public static string InValidMsg_FileInvalidFormat {
            get {
                return ResourceManager.GetString("InValidMsg_FileInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is empty, please check again.
        /// </summary>
        public static string InValidMsg_FileInvalidLenght {
            get {
                return ResourceManager.GetString("InValidMsg_FileInvalidLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file provided is invalid, only &apos;.xlsx&apos; files are accepted.
        /// </summary>
        public static string InValidMsg_FileInvalidType {
            get {
                return ResourceManager.GetString("InValidMsg_FileInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required.
        /// </summary>
        public static string InValidMsg_FullNameRequired {
            get {
                return ResourceManager.GetString("InValidMsg_FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name must not exceed 100 characters.
        /// </summary>
        public static string InValidMsg_FullNameTooLong {
            get {
                return ResourceManager.GetString("InValidMsg_FullNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen identification card must not exceed 25 characters.
        /// </summary>
        public static string InValidMsg_IdentityNumberTooLong {
            get {
                return ResourceManager.GetString("InValidMsg_IdentityNumberTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of issue cannot exceed 100 characters.
        /// </summary>
        public static string InValidMsg_IdentityPlaceTooLong {
            get {
                return ResourceManager.GetString("InValidMsg_IdentityPlaceTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported data is deleted from Cache.
        /// </summary>
        public static string InValidMsg_ImportDataNotExistInCache {
            get {
                return ResourceManager.GetString("InValidMsg_ImportDataNotExistInCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data import session expired.
        /// </summary>
        public static string InValidMsg_ImportTImeOut {
            get {
                return ResourceManager.GetString("InValidMsg_ImportTImeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth cannot be greater than current date.
        /// </summary>
        public static string InValidMsg_InValidDateOfBirth {
            get {
                return ResourceManager.GetString("InValidMsg_InValidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string InValidMsg_InvalidEmail {
            get {
                return ResourceManager.GetString("InValidMsg_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The issue date cannot be greater than the current date.
        /// </summary>
        public static string InValidMsg_InValidIdentityDate {
            get {
                return ResourceManager.GetString("InValidMsg_InValidIdentityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect information.
        /// </summary>
        public static string InValidMsg_InValidInformation {
            get {
                return ResourceManager.GetString("InValidMsg_InValidInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input error.
        /// </summary>
        public static string InValidMsg_InValidInput {
            get {
                return ResourceManager.GetString("InValidMsg_InValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee code must begin with the prefix &quot;NV-&quot;.
        /// </summary>
        public static string InValidMsg_InvalidPrefixEmployeeCode {
            get {
                return ResourceManager.GetString("InValidMsg_InvalidPrefixEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee code suffix must be digits.
        /// </summary>
        public static string InValidMsg_InvalidSuffixEmployeeCode {
            get {
                return ResourceManager.GetString("InValidMsg_InvalidSuffixEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect.
        /// </summary>
        public static string InValidMsg_LoginInfomation {
            get {
                return ResourceManager.GetString("InValidMsg_LoginInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data does not exist.
        /// </summary>
        public static string InValidMsg_NotExistInput {
            get {
                return ResourceManager.GetString("InValidMsg_NotExistInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identification number must only contain numeric characters.
        /// </summary>
        public static string InValidMsg_OnlyNumberIdentityNumber {
            get {
                return ResourceManager.GetString("InValidMsg_OnlyNumberIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone numbers must only contain numeric characters.
        /// </summary>
        public static string InValidMsg_OnlyNumberPhone {
            get {
                return ResourceManager.GetString("InValidMsg_OnlyNumberPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string InValidMsg_PasswordRequired {
            get {
                return ResourceManager.GetString("InValidMsg_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must not exceed 15 characters.
        /// </summary>
        public static string InValidMsg_PhoneNumberTooLong {
            get {
                return ResourceManager.GetString("InValidMsg_PhoneNumberTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position code is required.
        /// </summary>
        public static string InValidMsg_PositionCodeRequired {
            get {
                return ResourceManager.GetString("InValidMsg_PositionCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position code must not exceed 20 characters..
        /// </summary>
        public static string InValidMsg_PositionCodeTooLong {
            get {
                return ResourceManager.GetString("InValidMsg_PositionCodeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid position.
        /// </summary>
        public static string InValidMsg_PositionInvalid {
            get {
                return ResourceManager.GetString("InValidMsg_PositionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position name is required.
        /// </summary>
        public static string InValidMsg_PositionNameRequired {
            get {
                return ResourceManager.GetString("InValidMsg_PositionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error.
        /// </summary>
        public static string InValidMsg_SystemError {
            get {
                return ResourceManager.GetString("InValidMsg_SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InValidMsg_UnauthorizedUser {
            get {
                return ResourceManager.GetString("InValidMsg_UnauthorizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string InValidMsg_UserNameRequired {
            get {
                return ResourceManager.GetString("InValidMsg_UserNameRequired", resourceCulture);
            }
        }
    }
}
